# Generated by Django 6.0.1 on 2026-01-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supportmessage",
            old_name="is_read",
            new_name="is_from_admin",
        ),
        migrations.RemoveField(
            model_name="supportmessage",
            name="sender",
        ),
    ]
