# Generated by Django 6.0.1 on 2026-02-09 16:38

import support.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_rename_is_read_supportmessage_is_from_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportmessage",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to=support.models.support_upload_to
            ),
        ),
        migrations.AddField(
            model_name="supportmessage",
            name="attachment_mime",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="supportmessage",
            name="attachment_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
