# Generated by Django 6.0.1 on 2026-02-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_supportmessage_attachment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportchat",
            options={
                "verbose_name": "Чат поддержки",
                "verbose_name_plural": "Чаты поддержки",
            },
        ),
    ]
