# Generated by Django 6.0.1 on 2026-02-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0004_alter_supportchat_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportmessage",
            name="is_read_by_admin",
            field=models.BooleanField(default=False),
        ),
    ]
