# Generated by Django 6.0.1 on 2026-02-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Отзывы", "verbose_name_plural": "Отзывы"},
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
    ]
