# Generated by Django 6.0.1 on 2026-01-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("yandex", "Яндекс Доставка"),
                    ("ozon", "Ozon Доставка"),
                    ("post", "Почта России"),
                    ("cdek", "СДЭК"),
                ],
                default="courier",
                max_length=20,
                verbose_name="Способ доставки",
            ),
        ),
    ]
