# Generated by Django 6.0.1 on 2026-02-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_delivery_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="yandex_delivery_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Яндекс: стоимость доставки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="yandex_offer_raw",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Яндекс: оффер (сырой ответ)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="yandex_option_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Яндекс: выбранный вариант",
            ),
        ),
    ]
