# Generated by Django 6.0.1 on 2026-02-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_yandex_delivery_price_order_yandex_offer_raw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="yandex_pvz_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="yandex_pvz_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="yandex_pvz_payment_methods",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="yandex_pvz_position",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="yandex_pvz_type",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
