# Generated by Django 6.0.1 on 2026-02-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_yandex_pvz_address_order_yandex_pvz_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказа",
            },
        ),
        migrations.AlterModelOptions(
            name="returnrequest",
            options={
                "verbose_name": "Заявка на возврат",
                "verbose_name_plural": "Заявки на возврат",
            },
        ),
    ]
