# Generated by Django 5.1.1 on 2026-01-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_returnrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Промокод'),
        ),
    ]
