# Generated by Django 5.1.1 on 2026-01-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_phone_alter_returnrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
