# Generated by Django 5.1.1 on 2026-01-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_returnrequest_phone'),
        ('orders', '0016_add_updated_field'),
    ]

    operations = [
    ]
